### ISSUE TITLE
Next.js - support when hosting on Vercel?

### ISSUE THREAD

**Issue by WoetDev** [AikidoSec/firewall-node#317]
I setup the Firewall in a minimal Next.js application that I'm hosting on Vercel. 

I'm receiving events on the Aikido Dashboard when I run the application locally, but not receiving any events from my application on production hosted on Vercel (running Next 14.2.5 app router and my pages are on the Node runtime). 

My scripts I needed to get it working on development were also a bit more involved than the documentation described:

```
"scripts": {
    "build": "next build",
    "postbuild": "mkdir -p .next/standalone/node_modules/@aikidosec/firewall && cp -r node_modules/@aikidosec/firewall/* .next/standalone/node_modules/@aikidosec/firewall/",
    "lint": "next lint",
    "dev": "NODE_OPTIONS='-r dotenv/config -r @aikidosec/firewall' next dev",
    "start": "NODE_OPTIONS='-r dotenv/config -r @aikidosec/firewall' node .next/standalone/server.js"
  },
```

But at this point I'm not receiving any build errors and this does make it work on localhost, but still not receiving any events from prod, so I'm wondering if there's some caveat when hosting on Vercel?

**Comment by hansott** [comment]
Thanks for flagging the copy command, we've updated the docs: https://github.com/AikidoSec/firewall-node/pull/318/commits/10d76d511e72ba43491c713499e6aff3c72580af
